-- Validador de classificação: Supabase
-- Execute este arquivo no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.postagens_validacao (
  id bigint generated by default as identity primary key,
  candidato text,
  url text,
  caption text,
  likes bigint,
  "shortCode" text unique not null,
  comentarios bigint,
  data text,
  categoria text,
  validacao_1 text,
  subcategoria text,
  validacao_2 text,
  formato text,
  claimed_by uuid,
  claimed_at timestamptz,
  created_at timestamptz default now()
);

alter table public.postagens_validacao add column if not exists claimed_by uuid;
alter table public.postagens_validacao add column if not exists claimed_at timestamptz;
alter table public.postagens_validacao add column if not exists formato text;

insert into public.postagens_validacao (candidato,url,caption,likes,"shortCode",comentarios,data,categoria,validacao_1,subcategoria,validacao_2,formato)
values
('Zema','https://www.instagram.com/p/DckEikYpq1I/','Que tristeza viver num Brasil onde o líder máximo da nação é o maior mentiroso já visto.

Que tipo de referência é essa? Se ele tenta esconder, eu mostro.

Siga @romeuzemaoficial . CHEGA DE ESQUEMA.','169716','DckEikYpq1I','22246','2026-08-28 00:00:00 UTC','Conteúdo personalista',NULL,'Identidade',NULL,NULL),
('Zema','https://www.instagram.com/p/DckKlLwOlqb/','E agora, refrescou a memória aí?','74780','DckKlLwOlqb','5207','2026-08-28 00:00:00 UTC','Conteúdo personalista',NULL,'Relações pessoais e interpessoais',NULL,NULL),
('Zema','https://www.instagram.com/p/DcgxksZpGh6/','Miriam Leitão me atacou. É sério que alguém ainda acredita que isso é o mais grave nessa eleição?','67540','DcgxksZpGh6','4671','2026-08-26 00:00:00 UTC','Conteúdo personalista',NULL,'Relações pessoais e interpessoais',NULL,NULL),
('Zema','https://www.instagram.com/p/DckL3JBuhTc/','Agora tá explicado','57191','DckL3JBuhTc','3077','2026-08-28 00:00:00 UTC','Conteúdo personalista',NULL,'Identidade',NULL,NULL),
('Zema','https://www.instagram.com/p/Dccc6d9uRaR/','Essa é a soberania do Lula? É hora do Brasil acordar e parar de fingir que tá tudo bem.','50992','Dccc6d9uRaR','1516','2026-08-25 00:00:00 UTC','Conteúdo personalista',NULL,'Identidade',NULL,NULL),
('Zema','https://www.instagram.com/p/DcoQwlxOHcF/','Castração química, prisão pro resto da vida e FIM DA SAIDINHA. Se nada disso acontecer, esquece qualquer chance desse país dar certo.','49675','DcoQwlxOHcF','2714','2026-08-29 00:00:00 UTC','Conteúdo programático',NULL,'Propostas e soluções',NULL,NULL),
('Zema','https://www.instagram.com/p/Dcl1J2au5N1/','Haja companheiro… será que ele lembra de toda essa turma?','41957','Dcl1J2au5N1','2011','2026-08-28 00:00:00 UTC','Conteúdo personalista',NULL,'Relações pessoais e interpessoais',NULL,NULL),
('Zema','https://www.instagram.com/p/DcYuPAmOMME/','Já tá tão acostumado a mentir que a cara nem treme.

Mas pra cima de mim esse papinho não vai colar não.

A verdade é uma só. E o mineiro sabe muito bem o que o PT fez com Minas.

Eu consertei o estrago que sua companheirada causou, e agora vou fazer o mesmo com o Brasil.','36813','DcYuPAmOMME','3489','2026-08-23 00:00:00 UTC','Conteúdo personalista',NULL,'Competência',NULL,NULL),
('Zema','https://www.instagram.com/p/DccDGA0p_0A/','Tá chegando a hora. É 21h na Globo.','33700','DccDGA0p_0A','1486','2026-08-24 00:00:00 UTC','Conteúdo personalista',NULL,'Competência',NULL,NULL),
('Zema','https://www.instagram.com/p/Dcj_aeupM9Y/','Não vale a pena ver de novo.

Compartilhe. O TSE não quer que o Brasil veja esse conteúdo.','32355','Dcj_aeupM9Y','866','2026-08-27 00:00:00 UTC','Conteúdo personalista',NULL,'Relações pessoais e interpessoais',NULL,NULL)
on conflict ("shortCode") do nothing;

alter table public.postagens_validacao enable row level security;

drop policy if exists "read pending" on public.postagens_validacao;
create policy "read pending" on public.postagens_validacao
for select to authenticated
using (
  validacao_1 is null
  and validacao_2 is null
  and (claimed_by is null or claimed_by = auth.uid())
);

drop policy if exists "update claimed" on public.postagens_validacao;
create policy "update claimed" on public.postagens_validacao
for update to authenticated
using (claimed_by = auth.uid())
with check (claimed_by = auth.uid());

create or replace function public.claim_validation_items(p_limit int default 20)
returns setof public.postagens_validacao
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with picked as (
    select id
    from public.postagens_validacao
    where validacao_1 is null
      and validacao_2 is null
      and (claimed_by is null or claimed_at < now() - interval '30 minutes')
    order by id
    for update skip locked
    limit greatest(1, least(p_limit, 50))
  )
  update public.postagens_validacao p
     set claimed_by = auth.uid(), claimed_at = now()
    from picked
   where p.id = picked.id
  returning p.*;
end;
$$;

create or replace function public.save_validation(
  p_id bigint,
  p_validacao_1 text,
  p_validacao_2 text,
  p_formato text
)
returns public.postagens_validacao
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.postagens_validacao;
  original_categoria text;
  original_subcategoria text;
begin
  if p_validacao_1 is null or p_validacao_2 is null then
    raise exception 'Categoria e subcategoria precisam ser validadas.';
  end if;

  select categoria, subcategoria
    into original_categoria, original_subcategoria
    from public.postagens_validacao
   where id = p_id
     and claimed_by = auth.uid()
     and validacao_1 is null
     and validacao_2 is null;

  if original_categoria is null and original_subcategoria is null then
    raise exception 'Este item já foi validado ou não está reservado para este avaliador.';
  end if;

  -- validacao_1: OK ou uma categoria permitida.
  if p_validacao_1 not in ('OK','Conteúdo personalista','Conteúdo programático','Outros') then
    raise exception 'Categoria inválida.';
  end if;

  -- validacao_2: OK ou subcategoria da categoria escolhida, com Outros como exceção controlada.
  if p_validacao_2 not in ('OK','Identidade','Vida privada','Campanha negativa','Competência','Relações pessoais e interpessoais','Propostas e soluções','Mobilização política','Prestação de contas','Pautas e problemas políticos','Outros') then
    raise exception 'Subcategoria inválida.';
  end if;

  if p_validacao_1 <> 'OK' and p_validacao_2 = 'OK' then
    raise exception 'Ao corrigir a categoria, a subcategoria também precisa ser validada.';
  end if;

  if p_validacao_1 = 'OK' and p_validacao_2 <> 'OK' then
    if original_categoria = 'Conteúdo personalista' and p_validacao_2 not in ('Identidade','Vida privada','Campanha negativa','Competência','Relações pessoais e interpessoais','Outros') then
      raise exception 'Subcategoria incompatível com a categoria original.';
    end if;
    if original_categoria = 'Conteúdo programático' and p_validacao_2 not in ('Propostas e soluções','Mobilização política','Prestação de contas','Pautas e problemas políticos','Campanha negativa','Outros') then
      raise exception 'Subcategoria incompatível com a categoria original.';
    end if;
  end if;

  if p_validacao_1 = 'Conteúdo personalista' and p_validacao_2 not in ('Identidade','Vida privada','Campanha negativa','Competência','Relações pessoais e interpessoais','Outros') then
    raise exception 'Subcategoria incompatível com Conteúdo personalista.';
  end if;
  if p_validacao_1 = 'Conteúdo programático' and p_validacao_2 not in ('Propostas e soluções','Mobilização política','Prestação de contas','Pautas e problemas políticos','Campanha negativa','Outros') then
    raise exception 'Subcategoria incompatível com Conteúdo programático.';
  end if;
  if p_validacao_1 = 'Outros' and p_validacao_2 <> 'Outros' then
    raise exception 'Para a categoria Outros, use a subcategoria Outros.';
  end if;

  -- formato só admite a marcação Produzido por IA; NULL significa manter o atual.
  if p_formato is not null and p_formato <> 'Produzido por IA' then
    raise exception 'Formato de validação inválido.';
  end if;

  update public.postagens_validacao
     set validacao_1 = p_validacao_1,
         validacao_2 = p_validacao_2,
         formato = case when p_formato = 'Produzido por IA' then 'Produzido por IA' else formato end,
         claimed_by = null,
         claimed_at = null
   where id = p_id
     and claimed_by = auth.uid()
     and validacao_1 is null
     and validacao_2 is null
  returning * into result;

  if result.id is null then
    raise exception 'Este item já foi validado ou não está reservado para este avaliador.';
  end if;
  return result;
end;
$$;

revoke execute on function public.claim_validation_items(int) from public;
revoke execute on function public.save_validation(bigint,text,text,text) from public;
grant execute on function public.claim_validation_items(int) to authenticated;
grant execute on function public.save_validation(bigint,text,text,text) to authenticated;

-- IMPORTANTE: em Authentication > Providers, habilite Anonymous Sign-Ins.
